import { Video, Playlist } from "./types";

export const videoData: Video[] = [
  {
    id: "QqAvLkQwaek",
    title: "What is BIM in reality?",
    category: "OpenBIM",
    type: "reel",
    youtubeUrl: "https://youtube.com/shorts/QqAvLkQwaek",
    thumbnail: "https://img.youtube.com/vi/QqAvLkQwaek/hqdefault.jpg",
    instagramUrl:
      "https://www.instagram.com/modelflick/reel/DNJNxmMSl4a/",
    playlists: ["all", "featured", "openbim"],
  },
  {
    id: "Oz7wdg5fxcg",
    title: "What is OpenBIM",
    category: "OpenBIM",
    type: "reel",
    youtubeUrl: "https://youtube.com/shorts/Oz7wdg5fxcg",
    thumbnail: "https://img.youtube.com/vi/Oz7wdg5fxcg/hqdefault.jpg",
    instagramUrl:
      "https://www.instagram.com/reel/DN99rXsDL2C/?utm_source=ig_web_button_share_sheet",
    playlists: ["all", "openbim", "featured"],
  },
  
  {
    id: "DKrXsRJeM3w",
    title: "Go #OpenSource  Go #OpenBIM",
    category: "OpenBIM",
    type: "reel",
    youtubeUrl: "https://youtube.com/shorts/DKrXsRJeM3w",
    thumbnail: "https://img.youtube.com/vi/DKrXsRJeM3w/hqdefault.jpg",
    instagramUrl:
      "https://www.instagram.com/modelflick/reel/DMvasHHShB-/",
    playlists: ["all", "featured", "openbim"],
  },

  {
    id: "BSyPnYAFW9k",
    title: "LibreCAD installation",
    category: "OpenBIM",
    type: "video",
    youtubeUrl: "https://youtu.be/BSyPnYAFW9k",
    thumbnail: "https://img.youtube.com/vi/BSyPnYAFW9k/hqdefault.jpg",
    instagramUrl: "",
    playlists: ["all", "featured", "openbim", "2D", "install"],
  },

  {
    id: "vbqYWw27qFU",
    title: "Blender installation",
    category: "OpenBIM",
    type: "video",
    youtubeUrl: "https://youtu.be/vbqYWw27qFU",
    thumbnail: "https://img.youtube.com/vi/vbqYWw27qFU/hqdefault.jpg",
    instagramUrl: "",
    playlists: ["all", "featured", "install"],
  },


  {
    id: "ixMdxWLG-Lc",
    title: "How to Install Inkscape",
    category: "2d",
    type: "video",
    youtubeUrl: "https://youtu.be/ixMdxWLG-Lc",
    thumbnail: "https://img.youtube.com/vi/ixMdxWLG-Lc/hqdefault.jpg",
    instagramUrl: "",
    playlists: ["all",'featured', "2d",'install'],
  },
  {
    id: "eSuYss_iZsw",
    title: "Origin and Snap in Blender",
    category: "OpenBIM",
    type: "video",
    youtubeUrl: "https://youtu.be/eSuYss_iZsw",
    thumbnail: "https://img.youtube.com/vi/eSuYss_iZsw/hqdefault.jpg",
    instagramUrl: "",
    playlists: ["all", "blender", "blenderbasics"],
  },
  {
    id: "xx4FwsEz57M",
    title: "Snap settings in Blender",
    category: "OpenBIM",
    type: "video",
    youtubeUrl: "https://youtu.be/xx4FwsEz57M",
    thumbnail: "https://img.youtube.com/vi/xx4FwsEz57M/hqdefault.jpg",
    instagramUrl: "",
    playlists: ["all", "blender", "blenderbasics"],
  },
  {
    id: "QD673WsE1Fg",
    title: "Viewport Shading in Blender",
    category: "OpenBIM",
    type: "video",
    youtubeUrl: "https://youtu.be/QD673WsE1Fg",
    thumbnail: "https://img.youtube.com/vi/QD673WsE1Fg/hqdefault.jpg",
    instagramUrl: "",
    playlists: ["all", "blender", "blenderbasics"],
  },
  {
    id: "B1PxeWIOo_Y",
    title: "Edit Mode in Blender",
    category: "OpenBIM",
    type: "video",
    youtubeUrl: "https://youtu.be/B1PxeWIOo_Y",
    thumbnail: "https://img.youtube.com/vi/B1PxeWIOo_Y/hqdefault.jpg",
    instagramUrl: "",
    playlists: ["all", "blender", "blenderbasics"],
  },
  {
    id: "v3NCCqWpsr0",
    title: "Scale in Blender",
    category: "OpenBIM",
    type: "video",
    youtubeUrl: "https://youtu.be/v3NCCqWpsr0",
    thumbnail: "https://img.youtube.com/vi/v3NCCqWpsr0/hqdefault.jpg",
    instagramUrl: "",
    playlists: ["all", "blender", "blenderbasics"],
  },
  {
    id: "NGmAtaXXgcM",
    title: "Rotate in Blender",
    category: "OpenBIM",
    type: "video",
    youtubeUrl: "https://youtu.be/NGmAtaXXgcM",
    thumbnail: "https://img.youtube.com/vi/NGmAtaXXgcM/hqdefault.jpg",
    instagramUrl: "",
    playlists: ["all", "blender", "blenderbasics"],
  },
  {
    id: "bXG0Xsm8hXs",
    title: "Move in Blender",
    category: "OpenBIM",
    type: "video",
    youtubeUrl: "https://youtu.be/bXG0Xsm8hXs",
    thumbnail: "https://img.youtube.com/vi/bXG0Xsm8hXs/hqdefault.jpg",
    instagramUrl: "",
    playlists: ["all", "blender", "blenderbasics"],
  },
  {
    id: "9CceRC7ZZcw",
    title: "Blender Navigations",
    category: "OpenBIM",
    type: "video",
    youtubeUrl: "https://youtu.be/9CceRC7ZZcw",
    thumbnail: "https://img.youtube.com/vi/9CceRC7ZZcw/hqdefault.jpg",
    instagramUrl: "",
    playlists: ["all", "blender", "blenderbasics"],
  },
  {
    id: "Pc1m18ZVxVg",
    title: "CAD to blender",
    category: "OpenBIM",
    type: "video",
    youtubeUrl: "https://youtu.be/Pc1m18ZVxVg",
    thumbnail: "https://img.youtube.com/vi/Pc1m18ZVxVg/hqdefault.jpg",
    instagramUrl: "",
    playlists: ["openbim", "all", "blender"],
  },

  // New videos added below
  {
    id: "e3caD5gvxd8",
    title: "Model a Soap in Blender",
    category: "OpenBIM",
    type: "video",
    youtubeUrl: "https://youtu.be/e3caD5gvxd8",
    thumbnail: "https://img.youtube.com/vi/e3caD5gvxd8/hqdefault.jpg",
    instagramUrl: "",
    playlists: ["all", "blender", "modelling"],
  },
  {
    id: "WEcPjC4cmME",
    title: "Model a Baluster in Blender",
    category: "OpenBIM",
    type: "video",
    youtubeUrl: "https://youtu.be/WEcPjC4cmME",
    thumbnail: "https://img.youtube.com/vi/WEcPjC4cmME/hqdefault.jpg",
    instagramUrl: "",
    playlists: ["all", "blender", "modelling"],
  },
  {
    id: "2B2b4mi9iMc",
    title: "Rubiks Cube in Blender",
    category: "OpenBIM",
    type: "video",
    youtubeUrl: "https://youtu.be/2B2b4mi9iMc",
    thumbnail: "https://img.youtube.com/vi/2B2b4mi9iMc/hqdefault.jpg",
    instagramUrl: "",
    playlists: ["all", "blender", "modelling"],
  },
  
  {
    id: "OKhVrQ2Ti_A",
    title: "Model Table in Blender",
    category: "OpenBIM",
    type: "video",
    youtubeUrl: "https://youtu.be/OKhVrQ2Ti_A",
    thumbnail: "https://img.youtube.com/vi/OKhVrQ2Ti_A/hqdefault.jpg",
    instagramUrl: "",
    playlists: ["all", "blender", "modelling"],
  },
  {
    id: "dkVuUw-pXf0",
    title: "Blender Animation basics",
    category: "OpenBIM",
    type: "video",
    youtubeUrl: "https://youtu.be/dkVuUw-pXf0",
    thumbnail: "https://img.youtube.com/vi/dkVuUw-pXf0/hqdefault.jpg",
    instagramUrl: "",
    playlists: ["all", "blenderbasics", "blender"],
  },
  
];

export const playlists: Playlist[] = [
  { id: "openbim", title: "OpenBIM" },
  { id: "install", title: "Install" },
  { id: "blenderbasics", title: "Blenderbasics" },
  { id: "featured", title: "Featured" },
  { id: "modelling", title: "Modelling" },
  { id: "2d", title: "2D Graphics" },
  { id: "blender", title: "Blender" },
  { id: "all", title: "All Content" },
  
];
