// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar, Footer } from "@/components/common";
import Provider from "@/redux/provider";
import { Setup } from "@/components/utils";
import AuthGate from "@/components/utils/AuthGate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: '%s | Modelflick',
    default: 'Modelflick',
  },
  description: "Generated by Arunravikumar",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <Setup />
          <AuthGate>
            <Navbar />
            <div className="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8 my-8">
              {children}
            </div>
            <Footer />
          </AuthGate>
        </Provider>
      </body>
    </html>
  );
}