export const serviceComponents = [
  "Advance Payment and Site Visit",
  "Initial Sketch Design",
  "Final Plan after Revisions",
  "Government Permits and Approvals",
  "Structural Design and Calculations",
  "Door, Window & Grill Design",
  "Electrical Layout Plan",
  "Plumbing and Water System Plan",
  "Flooring and Tile Layout",
  "Toilet Design and Fittings",
  "Kitchen Layout and Design",
  "Wardrobe and Storage Design",
  "Interior Finishes and Materials",
  "Landscape Design",
  "Drawings for Government Completion Certificate",
  "Basic 3D Renders",
  "Specifications & Estimate",
  "Work Schedule",
  "Periodic Work Supervision",
];

export const feePercentages: Record<string, number> = {
  "Advance Payment and Site Visit": 5.0,
  "Initial Sketch Design": 12.0,
  "Final Plan after Revisions": 13.0,
  "Government Permits and Approvals": 5.0,
  "Structural Design and Calculations": 3.0,
  "Door, Window & Grill Design": 3.0,
  "Electrical Layout Plan": 5.0,
  "Plumbing and Water System Plan": 5.0,
  "Flooring and Tile Layout": 2.0,
  "Toilet Design and Fittings": 4.0,
  "Kitchen Layout and Design": 5.5,
  "Wardrobe and Storage Design": 3.5,
  "Interior Finishes and Materials": 3.0,
  "Landscape Design": 3.5,
  "Drawings for Government Completion Certificate": 2.5,
  "Basic 3D Renders": 10.0,
  "Specifications & Estimate": 2.0,
  "Work Schedule": 3.0,
  "Periodic Work Supervision": 10.0,
};

export const componentHierarchy: Record<string, number> = {
  "Advance Payment and Site Visit": 1,
  "Initial Sketch Design": 2,
  "Final Plan after Revisions": 3,
  "Government Permits and Approvals": 4,
  "Structural Design and Calculations": 4,
  "Door, Window & Grill Design": 4,
  "Electrical Layout Plan": 4,
  "Plumbing and Water System Plan": 4,
  "Flooring and Tile Layout": 4,
  "Toilet Design and Fittings": 4,
  "Kitchen Layout and Design": 4,
  "Wardrobe and Storage Design": 4,
  "Interior Finishes and Materials": 4,
  "Landscape Design": 4,
  "Drawings for Government Completion Certificate": 4,
  "Basic 3D Renders": 4,
  "Specifications & Estimate": 4,
  "Work Schedule": 4,
  "Periodic Work Supervision": 4,
};

export const componentDescriptions: Record<string, string> = {
  "Advance Payment and Site Visit": "An initial advance along with a site visit helps us understand your project context and requirements thoroughly.",
  "Initial Sketch Design": "We prepare basic conceptual sketches to translate your vision into an initial plan.",
  "Final Plan after Revisions": "Incorporates all required client revisions and finalizes the architectural plan.",
  "Government Permits and Approvals": "Includes preparation and submission of drawings/documents for necessary permits.",
  "Structural Design and Calculations": "Engineering calculations and structural drawings to ensure safety and stability.",
  "Door, Window & Grill Design": "Customized design of openings and grills for optimal aesthetics and ventilation.",
  "Electrical Layout Plan": "Detailed electrical circuit and switch layout for safe and convenient power distribution.",
  "Plumbing and Water System Plan": "Plan for water supply, drainage, and plumbing systems ensuring efficiency.",
  "Flooring and Tile Layout": "Layout plans for flooring patterns and tile positioning suited to your interiors.",
  "Toilet Design and Fittings": "Detailed WC, bath area, and sanitary fittings layout with ergonomic planning.",
  "Kitchen Layout and Design": "Functional and aesthetic kitchen plan including storage, sink, and appliance zones.",
  "Wardrobe and Storage Design": "Space-optimized storage and wardrobe layout for bedrooms and utility areas.",
  "Interior Finishes and Materials": "Specifications of surface finishes, paint, and textures tailored to your style.",
  "Landscape Design": "Plan for garden, hardscape, and outdoor spaces to complement your building.",
  "Drawings for Government Completion Certificate ": "All final drawings required for completion certificate is delivered.",
  "Basic 3D Renders": "Simple three-dimensional views to help visualize space and materials.",
  "Specifications & Estimate": "Bill of quantities and specifications for budgeting and material selection.",
  "Work Schedule": "Phased construction timeline and milestones for project monitoring.",
  "Periodic Work Supervision": "Periodic site visits to ensure work is executed as per design and quality standards.",
};

export const initialSelectedComponents = serviceComponents.reduce(
  (acc, service) => ({ ...acc, [service]: false }),
  {} as Record<string, boolean>
);
